# Generated by Django 3.2.6 on 2021-09-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=20)),
                ('emailInfo', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('desc', models.TextField(max_length=100)),
            ],
        ),
    ]
